USE mysql;

CREATE TABLE EMPLOYEE(
   ACCOUNT CHAR(30) NOT NULL,
   PWD CHAR(30),
   PRIMARY KEY (ACCOUNT));

INSERT INTO EMPLOYEE(ACCOUNT, PWD)
VALUES('root', 'password');

INSERT INTO EMPLOYEE(ACCOUNT, PWD)
VALUES('admin', 'admin_pwd');

INSERT INTO EMPLOYEE(ACCOUNT, PWD)
VALUES('user1', 'usr_pwd');